sudo: false
language: minimal
notifications:
  email: false
services:
- docker
os:
- linux
before_script:
  - docker pull tethysplatform/tethys-core || true
script:
  - cd ..
  - mv tethys src
  - cd ./src/docker
  - docker-compose build
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  provider: script
  script: docker push tethysplatform/tethys-core
  on:
    branch: automated_deployment
env:
  global:
    secure: BRmdxJszhsvtRdXH5rH5uM72mnhpms0Aqe99K3k8LOa4AyV5E72qOycUo/g5nqlatV+LXTwghnNjcEbRoNeBiRdhCwFG+uvk8FBCACmmprIPFjVWtW66F/fY1hhLDdg6+BlwTrUzJ1mY0+5G/CNoutsphLRS7mnR58LwEzhMCD1hPR8No1JSIQOzmydscZsuWDSrShtdOwheEMw9BVW2p+jnNNu9ahg6axmVGchO5hcHmQ3YU7dhU56CTt8LlXLWS+KtfUl3lKT8fJOwLsYdjP1MKqbQqiNb89Z2cgDuCoFFr3eqMBit4OvUNy7ujgSxuVbjtAG065dsiKcT45ewJV9NF2bc2yVZ+sZ5db8ywhrwnV0EIqHXxWKT9XYFmuAp+u5XrlGRv9d/R9l5wr6xmAoVet56N9JZMT/dS7sTFMrhMJJyB0+t9jkBfF5cyuEQiZMyMQFiEWttJ0JTDdb/8iZIWc0rk7sz61WiGW8tVprLdnPf7QKYLPtuAxxKyTzRdEBTvQGuGY1AYaUuznxhzthLs8GWEbNXUZ/A1mXICr1Rr+F8T2VrOKIOdpdd3J0k/5/x77GyeOVc5Xk3TTZzIahmeZqMHLzklE+a3ye+zVfAQIpcJu71oh+xYgimyJ2Fe11wozwBmh7gaH3GJxI8Xv5B6PnrxbbgiKyTSdKDDRU=
