version: "3.4"
services:
  tethys:
    container_name: tethys-custom
    image: tethys-custom
    build:
      context: ../
      target: app
      args:
        TETHYSBUILD_DB_USERNAME: tethys_admin
        TETHYSBUILD_DB_PASSWORD: tethys123
        TETHYSBUILD_DB_HOST: db
        TETHYSBUILD_DB_PORT: 5432
    volumes:
      # - ../tethys_apps:/usr/lib/tethys/src/tethys_apps
      # - ../tethys_portal:/usr/lib/tethys/src/tethys_portal
      - ../thredds/public/:/usr/lib/tethys/src/thredds/public/
      - ../production.yml/:/usr/lib/tethys/src/production.yml
    ports:
      - "8000:80"
    environment:
      CONDA_HOME: /opt/conda
      ALLOWED_HOSTS: '"[''127.0.0.1'', ''localhost'']"'
      TETHYS_SUPER_USER: "admin"
      TETHYS_SUPER_USER_PASS: "pass"
      TETHYS_MOUNT_PATH: "/tethys/indrhi"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tethys123
      POSTGRES_USER: tethys_admin
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:4.6.13
    restart: always
    ports:
      - "9000:8080"
      - "443:8443"
      - "8443:8443"
    volumes:
      - ../thredds/tomcat/logs/:/usr/local/tomcat/logs/
      - ../thredds/logs/:/usr/local/tomcat/content/thredds/logs/
      - ../thredds/cache/:/usr/local/tomcat/content/thredds/cache
      - ../thredds/public/:/usr/local/tomcat/content/thredds/public
      - ./thredds-config/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./thredds-config/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml


