apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-claim0
  name: db-claim0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: "db-volume"
  resources:
    requests:
      storage: 10Gi
status: {}
