kind: PersistentVolume
apiVersion: v1
metadata:
  name: thredds-data-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "../../thredds/public/"
