kind: PersistentVolume
apiVersion: v1
metadata:
  name: thredds-data-volume-2
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/root/tethys/tethys-docker/portal1/tethys/thredds/public"
